### ISSUE TITLE
Align with phonegap build to work without a www folder

### ISSUE THREAD

**Issue by hpssjellis** [phonegap/connect-phonegap#71] opened 2014-06-25 17:29 UTC
Phonegap build can compile a simple index.html file. Connect-phonegap dies unless the index.html file is in a sub folder called.

**Comment by filmaj** [comment] 2017-04-21 22:51
I believe this is a duplicate of #112. The "proper" way to go about handling this would be for connect-phonegap to look at the `<content>` tag to determine what to serve and from what root folder.

Closing. If you believe this issue is different from #112, please feel free to re-open and we can re-engage at that point.

**Closed by filmaj** 2017-04-21 22:51 UTC
Labels: enhancement
